/// Flutter icons CustomIcons
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData track_ales = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_sample = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pilot = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorbike_outline = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorbike = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_helmet = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_bourbonnais = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_bresse = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_carole = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_la_ferte_gaucher = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_ledenon = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_le_mans = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_magny_cours = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_misano = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_pouilly_en_auxois = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_vaison = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_dijon_prenois = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_barcelone = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_mirecourt = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_portimao = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
