/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData track_ledenon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_magny_cours = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_sample = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_vaison = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_carole = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_dijon_prenois = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_la_ferte_gaucher = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_bourbonnais = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_bresse = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_ales = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_le_mans = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pilot = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorbike_outline = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorbike = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_helmet = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_ales_simple = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_bresse_simple = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_dijon_simple = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_vaison_simple = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
