/// Flutter icons CustomIcons
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData helmet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData helmet_group = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorbike_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motorbike_plain = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pilot = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ales_track = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcelone_track = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bourbonnais_track = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bresse_track = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carole_track = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData default_track = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dijon_prenois_track = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ledenon_track = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData la_ferte_gaucher_track = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData le_mans_track = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magny_cours_track = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData misano_track = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mirecourt_track = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData portimao_track = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pouilly_en_auxois_track = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vaison_track = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
